### ISSUE TITLE
PARA TOMAR EN CUENTA

### ISSUE THREAD

**Issue by luisloro2710** [Via-Codigo/hojamembretada#1]
No funciona la opción para enumerar o colocar viñetas

**Comment by ondoheer** [comment]
Lecciones para abrir un issue:

1. Título descritivo del problema
2. Descripción del problema que permita replicarlo en el cuerpo del issue
3. Imagen si es posible.

En este caso no entiendo a que te refieres :P @luisloro2710

**Comment by ondoheer** [comment]
resuelto
